### ISSUE TITLE
玩家进入服务器疯狂报错

### ISSUE THREAD

**Issue by szzz666** [Physical-Science-Academy/NoCheatPlus#36]
[FATAL] Could not execute taskHandler 7: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket
10:55:15 [ERROR] Throwing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:42) ~[patched.jar:?]
        at cn.nukkit.Server.d(Server.java:922) ~[patched.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1151) ~[patched.jar:?]
        at cn.nukkit.Server.start(Server.java:1303) ~[patched.jar:?]
        at cn.nukkit.Server.<init>(Server.java:777) ~[patched.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:3) ~[patched.jar:?]
        at nukkit.pm1e.launcher.Main.lambda$start$0(Main.java:71) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket
        at net.catrainbow.nocheatplus.checks.NCPTickTask.handleWrapperInputPacket(NCPTickTask.kt:44) ~[?:?]
        at net.catrainbow.nocheatplus.checks.NCPTickTask.onRun(NCPTickTask.kt:35) ~[?:?]
        at cn.nukkit.scheduler.Task.run(Task.java:12) ~[patched.jar:?]
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:10) ~[patched.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:46) ~[patched.jar:?]
        ... 7 more
>

**Comment by Catrainbow233** [comment]
是从Jenkins下载的最新构建有这个问题吗

**Comment by szzz666** [comment]
是的

**Comment by Catrainbow233** [comment]
已解决，请在Jenkins下载最新版，需要删除旧配置文件

**Comment by szzz666** [comment]
at nukkit.pm1e.launcher.Main.lambda$start$0(Main.java:71) ~[?:?] 
 at java.lang.Thread.run(Thread.java:833) ~[?:?] 
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket 
 at net.catrainbow.nocheatplus.checks.NCPTickTask.handleWrapperInputPacket(NCPTickTask.kt:44) ~[?:?] 
 at net.catrainbow.nocheatplus.checks.NCPTickTask.onRun(NCPTickTask.kt:35) ~[?:?] 
 at cn.nukkit.scheduler.Task.run(Task.java:13) ~[patched.jar:?] 
 at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:4) ~[patched.jar:?] 
 at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:60) ~[patched.jar:?] 
 ... 7 more 
14:29:57 [FATAL] Could not execute taskHandler 9: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket 
14:29:57 [ERROR] Throwing 
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket 
 at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:14) ~[patched.jar:?] 
 at cn.nukkit.Server.a(Server.java:1100) ~[patched.jar:?] 
 at cn.nukkit.Server.tickProcessor(Server.java:252) ~[patched.jar:?] 
 at cn.nukkit.Server.start(Server.java:916) ~[patched.jar:?] 
 at cn.nukkit.Server.<init>(Server.java:1033) ~[patched.jar:?] 
 at cn.nukkit.Nukkit.main(Nukkit.java:70) ~[patched.jar:?] 
 at nukkit.pm1e.launcher.Main.lambda$start$0(Main.java:71) ~[?:?] 
 at java.lang.Thread.run(Thread.java:833) ~[?:?] 
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket 
 at net.catrainbow.nocheatplus.checks.NCPTickTask.handleWrapperInputPacket(NCPTickTask.kt:44) ~[?:?] 
 at net.catrainbow.nocheatplus.checks.NCPTickTask.onRun(NCPTickTask.kt:35) ~[?:?] 
 at cn.nukkit.scheduler.Task.run(Task.java:13) ~[patched.jar:?] 
 at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:4) ~[patched.jar:?] 
 at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:60) ~[patched.jar:?] 
 ... 7 more

**Comment by szzz666** [comment]
好像没有解决仍然出现，插件下载于https://ci.lanink.cn/job/NoCheatPlus/
删除过旧配置文件
14:23:44 [FATAL] Could not execute taskHandler 9: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket 
14:23:44 [ERROR] Throwing 
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket 
 at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:14) ~[patched.jar:?] 
 at cn.nukkit.Server.a(Server.java:1100) ~[patched.jar:?] 
 at cn.nukkit.Server.tickProcessor(Server.java:252) ~[patched.jar:?] 
 at cn.nukkit.Server.start(Server.java:916) ~[patched.jar:?] 
 at cn.nukkit.Server.<init>(Server.java:1033) ~[patched.jar:?] 
 at cn.nukkit.Nukkit.main(Nukkit.java:70) ~[patched.jar:?] 
 at nukkit.pm1e.launcher.Main.lambda$start$0(Main.java:71) ~[?:?] 
 at java.lang.Thread.run(Thread.java:833) ~[?:?] 
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket 
 at net.catrainbow.nocheatplus.checks.NCPTickTask.handleWrapperInputPacket(NCPTickTask.kt:44) ~[?:?] 
 at net.catrainbow.nocheatplus.checks.NCPTickTask.onRun(NCPTickTask.kt:35) ~[?:?] 
 at cn.nukkit.scheduler.Task.run(Task.java:13) ~[patched.jar:?] 
 at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:4) ~[patched.jar:?] 
 at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:60) ~[patched.jar:?] 
 ... 7 more
