### ISSUE TITLE
MOVING_MORE_PACKETS误判

### ISSUE THREAD

**Issue by Xiaochen6035** [Physical-Science-Academy/NoCheatPlus#52]
控制台报错：
2023-05-17 14:51:16.603 [main] FATAL - Could not execute taskHandler 18
java.lang.StackOverflowError: null
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.get(PropertiesUtil.java:483) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.access$200(PropertiesUtil.java:420) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.util.PropertiesUtil.getStringProperty(PropertiesUtil.java:368) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.util.PropertiesUtil.getBooleanProperty(PropertiesUtil.java:155) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.status.StatusLogger.isDebugPropertyEnabled(StatusLogger.java:120) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:403) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:344) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1930) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2805) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.handleLogMessageException(AbstractLogger.java:2225) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2208) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:750) ~[log4j-api-2.17.1.jar:2.17.1]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:582) ~[powernukkitx-1.19.80-r2.jar:?]
	at net.catrainbow.nocheatplus.compat.Bridge118$Companion.dataPacket(Bridge118.kt:141) ~[?:?]
	at net.catrainbow.nocheatplus.compat.Bridge118$Companion.setback(Bridge118.kt:71) ~[?:?]
	at net.catrainbow.nocheatplus.checks.moving.player.MorePackets.onCheck(MorePackets.kt:43) ~[?:?]
	at net.catrainbow.nocheatplus.checks.CheckListener.onTick(CheckListener.kt:37) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.checkEvent(NCPListener.kt:222) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.playerInputs(NCPListener.kt:247) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.access$playerInputs(NCPListener.kt:59) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$3.invoke(NCPListener.kt:101) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$3.invoke(NCPListener.kt:97) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$Companion.registerEvent$lambda-0(NCPListener.kt:78) ~[?:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61) ~[powernukkitx-1.19.80-r2.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:580) ~[powernukkitx-1.19.80-r2.jar:?]
	at net.catrainbow.nocheatplus.compat.Bridge118$Companion.dataPacket(Bridge118.kt:141) ~[?:?]
	at net.catrainbow.nocheatplus.compat.Bridge118$Companion.setback(Bridge118.kt:71) ~[?:?]
	at net.catrainbow.nocheatplus.checks.moving.player.MorePackets.onCheck(MorePackets.kt:43) ~[?:?]
	at net.catrainbow.nocheatplus.checks.CheckListener.onTick(CheckListener.kt:37) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.checkEvent(NCPListener.kt:222) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.playerInputs(NCPListener.kt:247) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.access$playerInputs(NCPListener.kt:59) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$3.invoke(NCPListener.kt:101) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$3.invoke(NCPListener.kt:97) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$Companion.registerEvent$lambda-0(NCPListener.kt:78) ~[?:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61) ~[powernukkitx-1.19.80-r2.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:580) ~[powernukkitx-1.19.80-r2.jar:?]
	at net.catrainbow.nocheatplus.compat.Bridge118$Companion.dataPacket(Bridge118.kt:141) ~[?:?]
	at net.catrainbow.nocheatplus.compat.Bridge118$Companion.setback(Bridge118.kt:71) ~[?:?]
	at net.catrainbow.nocheatplus.checks.moving.player.MorePackets.onCheck(MorePackets.kt:43) ~[?:?]
	at net.catrainbow.nocheatplus.checks.CheckListener.onTick(CheckListener.kt:37) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.checkEvent(NCPListener.kt:222) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.playerInputs(NCPListener.kt:247) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.access$playerInputs(NCPListener.kt:59) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$3.invoke(NCPListener.kt:101) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$3.invoke(NCPListener.kt:97) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$Companion.registerEvent$lambda-0(NCPListener.kt:78) ~[?:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61) ~[powernukkitx-1.19.80-r2.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:580) ~[powernukkitx-1.19.80-r2.jar:?]
	at net.catrainbow.nocheatplus.compat.Bridge118$Companion.dataPacket(Bridge118.kt:141) ~[?:?]
	at net.catrainbow.nocheatplus.compat.Bridge118$Companion.setback(Bridge118.kt:71) ~[?:?]
        ..............
	at net.catrainbow.nocheatplus.feature.NCPListener.checkEvent(NCPListener.kt:222) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.playerInputs(NCPListener.kt:247) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.access$playerInputs(NCPListener.kt:59) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$3.invoke(NCPListener.kt:101) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$3.invoke(NCPListener.kt:97) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$Companion.registerEvent$lambda-0(NCPListener.kt:78) ~[?:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61) ~[powernukkitx-1.19.80-r2.jar:?]
2023-05-17 14:51:16.642 [main] INFO  - §c§lAnti-cheat §7>> 被检测玩家:Xiaochen6035(Xiaochen6035),原因:MOVING_MORE_PACKETS | 728.8240000000009
2023-05-17 14:51:16.674 [main] INFO  - §c§lAnti-cheat §7>> 被检测玩家:Xiaochen6035(Xiaochen6035),原因:MOVING_MORE_PACKETS | 727.3663520000009
2023-05-17 14:51:16.725 [main] INFO  - §c§lAnti-cheat §7>> 被检测玩家:Xiaochen6035(Xiaochen6035),原因:MOVING_MORE_PACKETS | 725.9116192960009
2023-05-17 14:51:16.801 [main] INFO  - §l§cLeave §7>> 玩家 Xiaochen6035 §7断开连接

**Comment by Catrainbow233** [comment]
有复现方式吗

**Comment by Xiaochen6035** [comment]
> 有复现方式吗

从楼梯上跳下来，受到摔落伤害后就会判
