### ISSUE TITLE
玩家进入服务器作弊后报错

### ISSUE THREAD

**Issue by QN439751420** [Physical-Science-Academy/NoCheatPlus#53]
核心是1.19.80的mot（#136）
玩家进入服务器后作弊就报错
ncp是最新版的
日志：
---
2023-05-22 22:30:55.806 [main] INFO  - Done (15.039s)! For help, type "help"
2023-05-22 22:31:32.625 [main] INFO  - §bQNNB323§f[/127.0.0.1:55969] [Protocol Version:582 (1.19.80)] logged in
2023-05-22 22:31:38.133 [main] FATAL - Could not pass event 'cn.nukkit.event.player.PlayerTeleportEvent' to 'NoCheatPlus v1.0.0': null on net.catrainbow.nocheatplus.feature.NCPListener
2023-05-22 22:31:38.133 [main] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:512) [nukkit.jar:?]
	at cn.nukkit.Player.teleport(Player.java:5594) [nukkit.jar:?]
	at cn.nukkit.entity.Entity.teleport(Entity.java:2559) [nukkit.jar:?]
	at cn.nukkit.entity.Entity.teleport(Entity.java:2555) [nukkit.jar:?]
	at PG.ListenerA.join1(ListenerA.java:21) [BackToHub.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) [nukkit.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) [nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:512) [nukkit.jar:?]
	at cn.nukkit.Player.doFirstSpawn(Player.java:1011) [nukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:4290) [nukkit.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:199) [nukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:89) [nukkit.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:117) [nukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1339) [nukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1080) [nukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1048) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:765) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:82) [nukkit.jar:?]
Caused by: java.lang.NullPointerException
	at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:135) ~[?:?]
	at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:131) ~[?:?]
	at net.catrainbow.nocheatplus.checks.moving.MovingCheckListener.onTick(MovingCheckListener.kt:174) ~[?:?]
	at net.catrainbow.nocheatplus.checks.CheckListener.onTick(CheckListener.kt:34) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.checkEvent(NCPListener.kt:222) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.playerTeleports(NCPListener.kt:331) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit.jar:?]
	... 23 more
2023-05-22 22:31:38.165 [main] FATAL - Could not pass event 'cn.nukkit.event.player.PlayerTeleportEvent' to 'NoCheatPlus v1.0.0': null on net.catrainbow.nocheatplus.feature.NCPListener
2023-05-22 22:31:38.178 [main] ERROR - Throwing
java.lang.NullPointerException: null
	at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:135) ~[?:?]
	at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:131) ~[?:?]
	at net.catrainbow.nocheatplus.checks.moving.MovingCheckListener.onTick(MovingCheckListener.kt:174) ~[?:?]
	at net.catrainbow.nocheatplus.checks.CheckListener.onTick(CheckListener.kt:34) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.checkEvent(NCPListener.kt:222) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.playerTeleports(NCPListener.kt:331) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.access$playerTeleports(NCPListener.kt:59) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$15.invoke(NCPListener.kt:172) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$15.invoke(NCPListener.kt:168) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$Companion.registerEvent$lambda-0(NCPListener.kt:78) ~[?:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:512) [nukkit.jar:?]
	at cn.nukkit.Player.teleport(Player.java:5594) [nukkit.jar:?]
	at cn.nukkit.entity.Entity.teleport(Entity.java:2559) [nukkit.jar:?]
	at cn.nukkit.entity.Entity.teleport(Entity.java:2555) [nukkit.jar:?]
	at PG.ListenerA.join1(ListenerA.java:21) [BackToHub.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) [nukkit.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) [nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:512) [nukkit.jar:?]
	at cn.nukkit.Player.doFirstSpawn(Player.java:1011) [nukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:4290) [nukkit.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:199) [nukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:89) [nukkit.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:117) [nukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1339) [nukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1080) [nukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1048) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:765) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:82) [nukkit.jar:?]
2023-05-22 22:31:38.231 [main] FATAL - Could not pass event 'cn.nukkit.event.player.PlayerTeleportEvent' to 'NoCheatPlus v1.0.0': null on net.catrainbow.nocheatplus.feature.NCPListener
2023-05-22 22:31:38.248 [main] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:512) [nukkit.jar:?]
	at cn.nukkit.Player.teleport(Player.java:5594) [nukkit.jar:?]
	at cn.nukkit.entity.Entity.teleport(Entity.java:2563) [nukkit.jar:?]
	at net.catrainbow.nocheatplus.checks.net.PacketVerify$Companion.popVerifyQueue(PacketVerify.kt:180) [NoCheatPlus-1.0.0-.jar:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.playerJoins(NCPListener.kt:228) [NoCheatPlus-1.0.0-.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) [nukkit.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) [nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:512) [nukkit.jar:?]
	at cn.nukkit.Player.doFirstSpawn(Player.java:1011) [nukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:4290) [nukkit.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:199) [nukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:89) [nukkit.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:117) [nukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1339) [nukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1080) [nukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1048) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:765) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:82) [nukkit.jar:?]
Caused by: java.lang.NullPointerException
	at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:135) ~[?:?]
	at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:131) ~[?:?]
	at net.catrainbow.nocheatplus.checks.moving.MovingCheckListener.onTick(MovingCheckListener.kt:174) ~[?:?]
	at net.catrainbow.nocheatplus.checks.CheckListener.onTick(CheckListener.kt:34) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.checkEvent(NCPListener.kt:222) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.playerTeleports(NCPListener.kt:331) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit.jar:?]
	... 23 more
2023-05-22 22:31:38.249 [main] FATAL - Could not pass event 'cn.nukkit.event.player.PlayerTeleportEvent' to 'NoCheatPlus v1.0.0': null on net.catrainbow.nocheatplus.feature.NCPListener
2023-05-22 22:31:38.249 [main] ERROR - Throwing
java.lang.NullPointerException: null
	at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:135) ~[?:?]
	at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:131) ~[?:?]
	at net.catrainbow.nocheatplus.checks.moving.MovingCheckListener.onTick(MovingCheckListener.kt:174) ~[?:?]
	at net.catrainbow.nocheatplus.checks.CheckListener.onTick(CheckListener.kt:34) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.checkEvent(NCPListener.kt:222) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.playerTeleports(NCPListener.kt:331) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.access$playerTeleports(NCPListener.kt:59) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$15.invoke(NCPListener.kt:172) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$15.invoke(NCPListener.kt:168) ~[?:?]
	at net.catrainbow.nocheatplus.feature.NCPListener$Companion.registerEvent$lambda-0(NCPListener.kt:78) ~[?:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:512) [nukkit.jar:?]
	at cn.nukkit.Player.teleport(Player.java:5594) [nukkit.jar:?]
	at cn.nukkit.entity.Entity.teleport(Entity.java:2563) [nukkit.jar:?]
	at net.catrainbow.nocheatplus.checks.net.PacketVerify$Companion.popVerifyQueue(PacketVerify.kt:180) [NoCheatPlus-1.0.0-.jar:?]
	at net.catrainbow.nocheatplus.feature.NCPListener.playerJoins(NCPListener.kt:228) [NoCheatPlus-1.0.0-.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) [nukkit.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) [nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:512) [nukkit.jar:?]
	at cn.nukkit.Player.doFirstSpawn(Player.java:1011) [nukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:4290) [nukkit.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:199) [nukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:89) [nukkit.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:117) [nukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1339) [nukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1080) [nukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1048) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:765) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:82) [nukkit.jar:?]
2023-05-22 22:31:38.284 [main] INFO  - §eQNNB323 joined the game
2023-05-22 22:32:05.037 [main] INFO  - §eQNNB323 left the game
2023-05-22 22:32:05.053 [main] INFO  - §bQNNB323§f[/127.0.0.1:55969] logged out due to Disconnected from Server
2023-05-22 22:32:15.637 [main] INFO  - [CONSOLE: Stopping the server]

**Comment by Catrainbow233** [comment]
该报错暂不影响服务器正常运行。将会在下个版本中修复
