### ISSUE TITLE
MOVING_SURVIVAL_FLY误判

### ISSUE THREAD

**Issue by Stone72** [Physical-Science-Academy/NoCheatPlus#55]
21:09:01 [FATAL] Could not pass event 'cn.nukkit.event.player.PlayerTeleportEvent' to 'NoCheatPlus v1.0.0': null on net.catrainbow.nocheatplus.feature.NCPListener
21:09:01 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:7) ~[patched.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:15) ~[patched.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:177) ~[patched.jar:?]
        at cn.nukkit.Player.teleport(Player.java:1754) ~[patched.jar:?]
        at cn.nukkit.entity.Entity.teleport(Entity.java:580) ~[patched.jar:?]
        at net.catrainbow.nocheatplus.checks.net.PacketVerify$Companion.popVerifyQueue(PacketVerify.kt:180) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.feature.NCPListener.playerJoins(NCPListener.kt:228) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:14) ~[patched.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:15) ~[patched.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:177) ~[patched.jar:?]
        at cn.nukkit.Player.doFirstSpawn(Player.java:975) ~[patched.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:3114) ~[patched.jar:?]
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:129) ~[patched.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:80) ~[patched.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:229) ~[patched.jar:?]
        at cn.nukkit.Server.f(Server.java:592) ~[patched.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:504) ~[patched.jar:?]
        at cn.nukkit.Server.start(Server.java:368) ~[patched.jar:?]
        at cn.nukkit.Server.<init>(Server.java:761) ~[patched.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:43) ~[patched.jar:?]
        at nukkit.pm1e.launcher.Main.lambda$start$0(Main.java:71) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
        at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:135) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:131) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.checks.moving.MovingCheckListener.onTick(MovingCheckListener.kt:174) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.checks.CheckListener.onTick(CheckListener.kt:34) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.feature.NCPListener.checkEvent(NCPListener.kt:222) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.feature.NCPListener.playerTeleports(NCPListener.kt:331) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:14) ~[patched.jar:?]
        ... 25 more
21:09:01 [FATAL] Could not pass event 'cn.nukkit.event.player.PlayerTeleportEvent' to 'NoCheatPlus v1.0.0': null on net.catrainbow.nocheatplus.feature.NCPListener
21:09:01 [ERROR] Throwing
java.lang.NullPointerException: null
        at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:135) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.NoCheatPlus.getPlayerProvider(NoCheatPlus.kt:131) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.checks.moving.MovingCheckListener.onTick(MovingCheckListener.kt:174) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.checks.CheckListener.onTick(CheckListener.kt:34) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.feature.NCPListener.checkEvent(NCPListener.kt:222) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.feature.NCPListener.playerTeleports(NCPListener.kt:331) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.feature.NCPListener.access$playerTeleports(NCPListener.kt:59) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.feature.NCPListener$15.invoke(NCPListener.kt:172) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.feature.NCPListener$15.invoke(NCPListener.kt:168) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.feature.NCPListener$Companion.registerEvent$lambda-0(NCPListener.kt:78) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:15) ~[patched.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:177) ~[patched.jar:?]
        at cn.nukkit.Player.teleport(Player.java:1754) ~[patched.jar:?]
        at cn.nukkit.entity.Entity.teleport(Entity.java:580) ~[patched.jar:?]
        at net.catrainbow.nocheatplus.checks.net.PacketVerify$Companion.popVerifyQueue(PacketVerify.kt:180) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at net.catrainbow.nocheatplus.feature.NCPListener.playerJoins(NCPListener.kt:228) ~[NoCheatPlus-1.0.0-jar-with-dependencies.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:14) ~[patched.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:15) ~[patched.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:177) ~[patched.jar:?]
        at cn.nukkit.Player.doFirstSpawn(Player.java:975) ~[patched.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:3114) ~[patched.jar:?]
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:129) ~[patched.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:80) ~[patched.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:229) ~[patched.jar:?]
        at cn.nukkit.Server.f(Server.java:592) ~[patched.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:504) ~[patched.jar:?]
        at cn.nukkit.Server.start(Server.java:368) ~[patched.jar:?]
        at cn.nukkit.Server.<init>(Server.java:761) ~[patched.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:43) ~[patched.jar:?]
        at nukkit.pm1e.launcher.Main.lambda$start$0(Main.java:71) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
21:09:01 [INFO ] Player84787609 joined the game
21:09:05 [INFO ] NCP >>Player84787609 has been kicked for MOVING_SURVIVAL_FLY
21:09:05 [INFO ] NCP >>Player84787609 has been kicked for MOVING_SURVIVAL_FLY
21:09:05 [INFO ] NCP >>Player84787609 has been kicked for MOVING_SURVIVAL_FLY
21:09:05 [INFO ] NCP >>Player84787609 has been kicked for MOVING_SURVIVAL_FLY
21:09:05 [INFO ] Player84787609 left the game
21:09:05 [INFO ] Player84787609[/39.148.164.92:55536] logged out due to Disconnected from Server

**Comment by Stone72** [comment]
疾跑加跳误判成飞
ncpconfig.yml文件为默认

**Comment by Stone72** [comment]
走加跳也误判成飞

**Comment by Catrainbow233** [comment]
什么核心，游戏版本，触发方式提供下

**Comment by Stone72** [comment]
PM1E核心

**Comment by Stone72** [comment]
1.19.80.2770版本
