### ISSUE TITLE
关于WrapperInputPacket的报错

### ISSUE THREAD

**Issue by CoolMagic233** [Physical-Science-Academy/NoCheatPlus#72]
在已被关闭的issue中，已发现有用户反馈此报错，但未解决该问题
1.即使使用构建站最新的构建ncp和最新的pm1e-mot依然报错(已删除旧的配置文件)
2.循环报错下，客户端在默认世界交互会导致客户端异常崩溃
异常如下:
[ERROR] Throwing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:243) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1359) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1090) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:1058) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:775) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:82) [Nukkit-MOT-SNAPSHOT.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket
        at net.catrainbow.nocheatplus.checks.NCPTickTask.handleWrapperInputPacket(NCPTickTask.kt:44) ~[?:?]
        at net.catrainbow.nocheatplus.checks.NCPTickTask.onRun(NCPTickTask.kt:35) ~[?:?]
        at cn.nukkit.scheduler.Task.run(Task.java:52) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:240) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        ... 5 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(java.lang.Class, java.lang.String, java.lang.String, int)' [in thread "main"]
        at net.catrainbow.nocheatplus.feature.wrapper.WrapperInputPacket.<clinit>(WrapperInputPacket.kt:31) ~[?:?]
        at net.catrainbow.nocheatplus.checks.NCPTickTask.handleWrapperInputPacket(NCPTickTask.kt:44) ~[?:?]
        at net.catrainbow.nocheatplus.checks.NCPTickTask.onRun(NCPTickTask.kt:35) ~[?:?]
        at cn.nukkit.scheduler.Task.run(Task.java:52) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:240) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        ... 5 more

**Comment by Catrainbow233** [comment]
端午节集中修复

**Comment by Catrainbow233** [comment]
最新版测试后无法复现，请再测试后若还有问题再反馈

**Comment by CoolMagic233** [comment]
> 最新版测试后无法复现，请再测试后若还有问题再反馈

![image](https://github.com/Physical-Science-Academy/NoCheatPlus/assets/91107923/51bb0b4c-299c-4d4a-b80d-6fece242d316)
是否可以透露下你的复现环境，在保持最新的服务端软件和ncp的情况下，普通的客户端进入服务器依然出现此问题，最后导致服务器崩溃.
